/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as EmployeesIndexRouteImport } from './routes/employees.index'
import { Route as MyTasksTaskIdRouteImport } from './routes/my-tasks_.$taskId'
import { Route as EmployeesRolesRouteImport } from './routes/employees.roles'
import { Route as ClientsNewRouteImport } from './routes/clients_.new'
import { Route as ProjectsIdSetupRouteImport } from './routes/projects_.$id.setup'
import { Route as EmployeesRolesNewRouteImport } from './routes/employees.roles_.new'
import { Route as EmployeesRolesIdRouteImport } from './routes/employees.roles_.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeesRoute,
} as any)
const MyTasksTaskIdRoute = MyTasksTaskIdRouteImport.update({
  id: '/my-tasks_/$taskId',
  path: '/my-tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRolesRoute = EmployeesRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => EmployeesRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients_/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdSetupRoute = ProjectsIdSetupRouteImport.update({
  id: '/projects_/$id/setup',
  path: '/projects/$id/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRolesNewRoute = EmployeesRolesNewRouteImport.update({
  id: '/roles_/new',
  path: '/roles/new',
  getParentRoute: () => EmployeesRoute,
} as any)
const EmployeesRolesIdRoute = EmployeesRolesIdRouteImport.update({
  id: '/roles_/$id',
  path: '/roles/$id',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/employee': typeof EmployeeRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/games': typeof GamesRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/reviews': typeof ReviewsRoute
  '/team': typeof TeamRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/roles': typeof EmployeesRolesRoute
  '/my-tasks/$taskId': typeof MyTasksTaskIdRoute
  '/employees/': typeof EmployeesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/employees/roles/$id': typeof EmployeesRolesIdRoute
  '/employees/roles/new': typeof EmployeesRolesNewRoute
  '/projects/$id/setup': typeof ProjectsIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/employee': typeof EmployeeRoute
  '/games': typeof GamesRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/reviews': typeof ReviewsRoute
  '/team': typeof TeamRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/roles': typeof EmployeesRolesRoute
  '/my-tasks/$taskId': typeof MyTasksTaskIdRoute
  '/employees': typeof EmployeesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/employees/roles/$id': typeof EmployeesRolesIdRoute
  '/employees/roles/new': typeof EmployeesRolesNewRoute
  '/projects/$id/setup': typeof ProjectsIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clients': typeof ClientsRoute
  '/employee': typeof EmployeeRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/games': typeof GamesRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/reviews': typeof ReviewsRoute
  '/team': typeof TeamRoute
  '/clients_/new': typeof ClientsNewRoute
  '/employees/roles': typeof EmployeesRolesRoute
  '/my-tasks_/$taskId': typeof MyTasksTaskIdRoute
  '/employees/': typeof EmployeesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/employees/roles_/$id': typeof EmployeesRolesIdRoute
  '/employees/roles_/new': typeof EmployeesRolesNewRoute
  '/projects_/$id/setup': typeof ProjectsIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clients'
    | '/employee'
    | '/employees'
    | '/games'
    | '/manager'
    | '/my-tasks'
    | '/reviews'
    | '/team'
    | '/clients/new'
    | '/employees/roles'
    | '/my-tasks/$taskId'
    | '/employees/'
    | '/projects/'
    | '/employees/roles/$id'
    | '/employees/roles/new'
    | '/projects/$id/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clients'
    | '/employee'
    | '/games'
    | '/manager'
    | '/my-tasks'
    | '/reviews'
    | '/team'
    | '/clients/new'
    | '/employees/roles'
    | '/my-tasks/$taskId'
    | '/employees'
    | '/projects'
    | '/employees/roles/$id'
    | '/employees/roles/new'
    | '/projects/$id/setup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clients'
    | '/employee'
    | '/employees'
    | '/games'
    | '/manager'
    | '/my-tasks'
    | '/reviews'
    | '/team'
    | '/clients_/new'
    | '/employees/roles'
    | '/my-tasks_/$taskId'
    | '/employees/'
    | '/projects/'
    | '/employees/roles_/$id'
    | '/employees/roles_/new'
    | '/projects_/$id/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientsRoute: typeof ClientsRoute
  EmployeeRoute: typeof EmployeeRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  GamesRoute: typeof GamesRoute
  ManagerRoute: typeof ManagerRoute
  MyTasksRoute: typeof MyTasksRoute
  ReviewsRoute: typeof ReviewsRoute
  TeamRoute: typeof TeamRoute
  ClientsNewRoute: typeof ClientsNewRoute
  MyTasksTaskIdRoute: typeof MyTasksTaskIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdSetupRoute: typeof ProjectsIdSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/my-tasks_/$taskId': {
      id: '/my-tasks_/$taskId'
      path: '/my-tasks/$taskId'
      fullPath: '/my-tasks/$taskId'
      preLoaderRoute: typeof MyTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/roles': {
      id: '/employees/roles'
      path: '/roles'
      fullPath: '/employees/roles'
      preLoaderRoute: typeof EmployeesRolesRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/clients_/new': {
      id: '/clients_/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$id/setup': {
      id: '/projects_/$id/setup'
      path: '/projects/$id/setup'
      fullPath: '/projects/$id/setup'
      preLoaderRoute: typeof ProjectsIdSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/roles_/new': {
      id: '/employees/roles_/new'
      path: '/roles/new'
      fullPath: '/employees/roles/new'
      preLoaderRoute: typeof EmployeesRolesNewRouteImport
      parentRoute: typeof EmployeesRoute
    }
    '/employees/roles_/$id': {
      id: '/employees/roles_/$id'
      path: '/roles/$id'
      fullPath: '/employees/roles/$id'
      preLoaderRoute: typeof EmployeesRolesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesRolesRoute: typeof EmployeesRolesRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  EmployeesRolesIdRoute: typeof EmployeesRolesIdRoute
  EmployeesRolesNewRoute: typeof EmployeesRolesNewRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesRolesRoute: EmployeesRolesRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  EmployeesRolesIdRoute: EmployeesRolesIdRoute,
  EmployeesRolesNewRoute: EmployeesRolesNewRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientsRoute: ClientsRoute,
  EmployeeRoute: EmployeeRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  GamesRoute: GamesRoute,
  ManagerRoute: ManagerRoute,
  MyTasksRoute: MyTasksRoute,
  ReviewsRoute: ReviewsRoute,
  TeamRoute: TeamRoute,
  ClientsNewRoute: ClientsNewRoute,
  MyTasksTaskIdRoute: MyTasksTaskIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdSetupRoute: ProjectsIdSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
